In [1]:
import pandas as pd #数据分析
import numpy as np #科学计算
data=pd.read_csv("/Users/xwx/Desktop/kaggle/tatanic/data/train.csv")
data=data[0:15]

# 数的操作

In [ ]:
函数	说明
abs、fabs	计算整数、浮点数或复数的绝对值。对于复数数值，可以使用更快的fabs。
sqrt	计算各元素的平方根
square	计算各元素的平方
exp	计算各元素的指数e^x
log、log10、log2、log1p	分别为自然对数、底数为10的log、底数为2的log、log(1 + x)
sign	计算各元素的正负号：1（正数）、0（零）、-1（负数）
ceil	计算各元素的ceiling值
floor	计算各元素的floor值
rint	四舍五入到正数，保留dtype
modf	将数组的小数和整数部分以两个独立数组的形式返回
isnan	返回一个表示“哪些值是NaN”的布尔型数组
isfinite、isinf	分别返回一个表示“哪些元素是有穷的”或“哪些元素是无穷的”的布尔型数组
cos、cosh、sin、sinh、tan、tanh	普通型和双曲型三角函数
arccos、arccosh、arcsin、arcsinh、arctan、arctanh	反三角函数
logical_not	计算各元素not x的真值。想到与-arr


# 单个数组的操作

In [11]:
#生成特定多维数组
print(np.zeros((3,2,2),dtype=int))#三维全o数组
print(np.ones((2,2),dtype=int))#二维全1数组
print(np.eye(5,dtype=int))#单位矩阵

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[1 1]
 [1 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [12]:
#返回数组中非零元素的索引值
a = np.array([[0,0,3],[0,0,0],[0,0,9]])
b = np.nonzero(a)
print(np.array(b).ndim)
print(b)
print(np.transpose(np.nonzero(a)))

2
(array([0, 2]), array([2, 2]))
[[0 2]
 [2 2]]


In [18]:
#返回array中元素的index
a = np.array(([3,2,1],[2,5,7],[4,7,8])) 
index = np.argwhere(a == 7) 
print(index) 
print(a)

[[1 2]
 [2 1]]
[[3 2 1]
 [2 5 7]
 [4 7 8]]


1）a中有2个非零元素，因此，索引值tuple中array的长度为2。因为，只有非零元素才有索引值。
2）索引值数组是2 维的。实际上，无论a的维度是多少，索引值数组一定是2维的tuple，但是tuple中的一维array个数和a的维数一致。
3）第1个array([0, 2])是从row值上对3和9进行的描述
。第2个array([2, 2])是从col值上对3和9的描述。这样，从行和列上两个维度上各用一个数组来描述非零索引值。
4）通过调用np.transpose()函数，得出3的索引值是[0 2]
，即第0行，第2列。

In [ ]:
a = np.arange(10,100,5)
print(a)
print('向量大小:',a.size)
a36 = a.reshape(3,6)
print(a36)
print('-------------------')
print('求和:',a36.sum())
print('按行求和:',a36.sum(axis=1))
print('按列求和:',a36.sum(axis=0))
print('最大值:',a36.max())
print('每行最大值:',a36.max(axis=1))
print('每列最大值:',a36.max(axis=0))
print('最小值:',a36.min())
print('每行最小值:',a36.min(axis=1))
print('每列最小值:',a36.min(axis=0))
print('平均值:',a36.mean())
print('每行平均值:',a36.mean(axis=1))
print('每列平均值:',a36.mean(axis=0))
print('最大值索引:',a36.argmax())
print('每行最大值索引:',a36.argmax(axis=1))
print('每列最大值索引:',a36.argmax(axis=0))
print('log值:',np.log(a36))
print('log10值:',np.log10(a36))
print('log2值:',np.log2(a36))
print('指数值:',np.exp(a36))
print('平方根:',np.sqrt(a36))
print('--------------------')
a = np.random.random((3,4))*10
print(a)
print('小数向下取整:',np.floor(a))
print('小数向上取整:',np.ceil(a))

In [6]:
a = np.array([[1, 2], [3, 4]])
#求均值 每行一个
np.mean(a,axis=1)
#求均值 每列一个
np.mean(a,axis=0)

#求方差 整体方差
np.std(a)

1.118033988749895

In [ ]:
#多维数组变一维
arr4=np.array([[65,76,89,91],[31,42,45,61]],float)
arr4.flatten()

In [ ]:
#删除某行
dataset=[[1,2,3],[2,3,4],[4,5,6]]
d1= np.delete(dataset, 1, axis=0)#删除某一行
d2=np.delete(dataset, [1,2], axis=0)#删除多行
#删除某列
dataset=[[1,2,3],[2,3,4],[4,5,6]]
d3= np.delete(dataset, -1, axis=1)#删除某一列
d4=np.delete(dataset, [1,2], axis=1)#删除多列

# 多个数组之间操作

In [7]:
#数组的拼接合并
a = np.array(([1,2,3],[2,3,4],[3,4,5]))
b=a*2
#水平组合
np.hstack((a,b))
print(np.concatenate((a,b),axis=1))
#垂直组合
np.vstack((a,b))
print(np.concatenate((a,b),axis=0))
#沿着纵轴方向组合
np.dstack((a,b))


[[ 1  2  3  2  4  6]
 [ 2  3  4  4  6  8]
 [ 3  4  5  6  8 10]]
[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]


array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 2,  4],
        [ 3,  6],
        [ 4,  8]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]]])

In [59]:
#求两个数组的交并集
a = np.array(([1,3,2],[0,4,0]))
b=np.array(([1,2,4],[1,4,0]))
#求交集
A = [i for i in a[0] if i in b[0]]
#求并集
B = np.array(list(set(a[0]).union(set(b[0]))))
B

array([[ True,  True,  True],
       [ True,  True,  True]])

In [61]:
#判断两个矩阵是否相等
a = np.array(([1,3,2],[0,4,0]))
b=np.array(([1,2,4],[1,4,0]))
print(a==b)#用==判断只能返回一个判断矩阵，表示其中每一个元素是否对应相等
print((a==b).all())#如果两个矩阵中的所有元素对应相等，则返回True，反之返回False
print((a==b).any())#如果判断两个矩阵中是否有相等的元素，有任何一个相等就行，这种情况就可以用.any()

[[ True False False]
 [False  True  True]]
False
True
